name: Test Python

on:
  push:

permissions:
  contents: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Run Tests
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Build package
      run: |
          python -m pytest exercise1.py          
          python -m pytest exercise2.py          
          python -m pytest exercise3.py
